// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package tutorial

import (
	"bytes"
	"reflect"
	"context"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

type Int int32

func IntPtr(v Int) *Int { return &v }

type MultiplicationService interface {
  // Parameters:
  //  - N1
  //  - N2
  Multiply(ctx context.Context, n1 Int, n2 Int) (r Int, err error)
}

type MultiplicationServiceClient struct {
  c thrift.TClient
}

// Deprecated: Use NewMultiplicationService instead
func NewMultiplicationServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *MultiplicationServiceClient {
  return &MultiplicationServiceClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

// Deprecated: Use NewMultiplicationService instead
func NewMultiplicationServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *MultiplicationServiceClient {
  return &MultiplicationServiceClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewMultiplicationServiceClient(c thrift.TClient) *MultiplicationServiceClient {
  return &MultiplicationServiceClient{
    c: c,
  }
}

// Parameters:
//  - N1
//  - N2
func (p *MultiplicationServiceClient) Multiply(ctx context.Context, n1 Int, n2 Int) (r Int, err error) {
  var _args0 MultiplicationServiceMultiplyArgs
  _args0.N1 = n1
  _args0.N2 = n2
  var _result1 MultiplicationServiceMultiplyResult
  if err = p.c.Call(ctx, "multiply", &_args0, &_result1); err != nil {
    return
  }
  return _result1.GetSuccess(), nil
}

type MultiplicationServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler MultiplicationService
}

func (p *MultiplicationServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *MultiplicationServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *MultiplicationServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewMultiplicationServiceProcessor(handler MultiplicationService) *MultiplicationServiceProcessor {

  self2 := &MultiplicationServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self2.processorMap["multiply"] = &multiplicationServiceProcessorMultiply{handler:handler}
return self2
}

func (p *MultiplicationServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err := iprot.ReadMessageBegin()
  if err != nil { return false, err }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(thrift.STRUCT)
  iprot.ReadMessageEnd()
  x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
  x3.Write(oprot)
  oprot.WriteMessageEnd()
  oprot.Flush()
  return false, x3

}

type multiplicationServiceProcessorMultiply struct {
  handler MultiplicationService
}

func (p *multiplicationServiceProcessorMultiply) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := MultiplicationServiceMultiplyArgs{}
  if err = args.Read(iprot); err != nil {
    iprot.ReadMessageEnd()
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
    oprot.WriteMessageBegin("multiply", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush()
    return false, err
  }

  iprot.ReadMessageEnd()
  result := MultiplicationServiceMultiplyResult{}
var retval Int
  var err2 error
  if retval, err2 = p.handler.Multiply(ctx, args.N1, args.N2); err2 != nil {
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing multiply: " + err2.Error())
    oprot.WriteMessageBegin("multiply", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush()
    return true, err2
  } else {
    result.Success = &retval
}
  if err2 = oprot.WriteMessageBegin("multiply", thrift.REPLY, seqId); err2 != nil {
    err = err2
  }
  if err2 = result.Write(oprot); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.Flush(); err == nil && err2 != nil {
    err = err2
  }
  if err != nil {
    return
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - N1
//  - N2
type MultiplicationServiceMultiplyArgs struct {
  N1 Int `thrift:"n1,1" db:"n1" json:"n1"`
  N2 Int `thrift:"n2,2" db:"n2" json:"n2"`
}

func NewMultiplicationServiceMultiplyArgs() *MultiplicationServiceMultiplyArgs {
  return &MultiplicationServiceMultiplyArgs{}
}


func (p *MultiplicationServiceMultiplyArgs) GetN1() Int {
  return p.N1
}

func (p *MultiplicationServiceMultiplyArgs) GetN2() Int {
  return p.N2
}
func (p *MultiplicationServiceMultiplyArgs) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField2(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *MultiplicationServiceMultiplyArgs)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  temp := Int(v)
  p.N1 = temp
}
  return nil
}

func (p *MultiplicationServiceMultiplyArgs)  ReadField2(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  temp := Int(v)
  p.N2 = temp
}
  return nil
}

func (p *MultiplicationServiceMultiplyArgs) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("multiply_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *MultiplicationServiceMultiplyArgs) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("n1", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:n1: ", p), err) }
  if err := oprot.WriteI32(int32(p.N1)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.n1 (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:n1: ", p), err) }
  return err
}

func (p *MultiplicationServiceMultiplyArgs) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("n2", thrift.I32, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:n2: ", p), err) }
  if err := oprot.WriteI32(int32(p.N2)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.n2 (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:n2: ", p), err) }
  return err
}

func (p *MultiplicationServiceMultiplyArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("MultiplicationServiceMultiplyArgs(%+v)", *p)
}

// Attributes:
//  - Success
type MultiplicationServiceMultiplyResult struct {
  Success *Int `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewMultiplicationServiceMultiplyResult() *MultiplicationServiceMultiplyResult {
  return &MultiplicationServiceMultiplyResult{}
}

var MultiplicationServiceMultiplyResult_Success_DEFAULT Int
func (p *MultiplicationServiceMultiplyResult) GetSuccess() Int {
  if !p.IsSetSuccess() {
    return MultiplicationServiceMultiplyResult_Success_DEFAULT
  }
return *p.Success
}
func (p *MultiplicationServiceMultiplyResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *MultiplicationServiceMultiplyResult) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField0(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *MultiplicationServiceMultiplyResult)  ReadField0(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(); err != nil {
  return thrift.PrependError("error reading field 0: ", err)
} else {
  temp := Int(v)
  p.Success = &temp
}
  return nil
}

func (p *MultiplicationServiceMultiplyResult) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("multiply_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *MultiplicationServiceMultiplyResult) writeField0(oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin("success", thrift.I32, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := oprot.WriteI32(int32(*p.Success)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.success (0) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *MultiplicationServiceMultiplyResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("MultiplicationServiceMultiplyResult(%+v)", *p)
}


